// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3r-pzSVgVyV0lNjz6XZqLH0u2Xrq4jko',
    appId: '1:865506323381:web:ac35ccc9c40b7c2e43c7fc',
    messagingSenderId: '865506323381',
    projectId: 'chat-app-6e7a7',
    authDomain: 'chat-app-6e7a7.firebaseapp.com',
    storageBucket: 'chat-app-6e7a7.appspot.com',
    measurementId: 'G-8NSW0PJCB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChLKkA0CIpLA0oMPcPQ0I8PzGxhLy1rs4',
    appId: '1:865506323381:android:0a748b45d6cba5fc43c7fc',
    messagingSenderId: '865506323381',
    projectId: 'chat-app-6e7a7',
    storageBucket: 'chat-app-6e7a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjEF4xQ2sqg3rBV2vXPUqxrNtlyz_Nqgk',
    appId: '1:865506323381:ios:853a639a811c198043c7fc',
    messagingSenderId: '865506323381',
    projectId: 'chat-app-6e7a7',
    storageBucket: 'chat-app-6e7a7.appspot.com',
    iosClientId: '865506323381-nrmvn6kngd361j065ve14ghiev65s7gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjEF4xQ2sqg3rBV2vXPUqxrNtlyz_Nqgk',
    appId: '1:865506323381:ios:853a639a811c198043c7fc',
    messagingSenderId: '865506323381',
    projectId: 'chat-app-6e7a7',
    storageBucket: 'chat-app-6e7a7.appspot.com',
    iosClientId: '865506323381-nrmvn6kngd361j065ve14ghiev65s7gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
